### ISSUE TITLE
完美的功能

### ISSUE THREAD

**Issue by chengkongyiban** [nameking77/shadowrocket#1]
配合酷我纯净版，算是最适合国人的音乐app了，只是会覆盖其他模块的主机名，希望能添加下代码，另外酷我激活了王卡免流之后，在数据流量的情况下开启VPN就会无法联网，跟模块无关，但是希望大佬可以研究下，这样就完美无缺了

**Comment by nameking77** [comment]
> 配合酷我纯净版，算是最适合国人的的音乐app了，只是会覆盖其他模块的主机名，希望能添加下代码，另外酷我激活了王卡免流后，在数据流量的情况下打开VPN将无法联网，跟模块无关，但希望大佬可以研究下，这样就完美无缺了

主机名问题可以自己配置，免流问题 可通过免流节点解决

**Comment by chengkongyiban** [comment]
谢谢大佬解答
